require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false
