require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/bundle/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*

Style/Documentation:
  Enabled: false
